[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]
aptPkgs = ["python3-dev"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]