# Generated by Django 4.2.16 on 2024-10-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=500, null=True)),
                ('zoom_id', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('registration_time', models.CharField(max_length=100)),
                ('join_time', models.CharField(max_length=100)),
                ('leave_time', models.CharField(max_length=100)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('attended', models.CharField(max_length=100)),
            ],
        ),
    ]
