# Generated by Django 4.2.16 on 2024-10-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcludedIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name="registration",
            old_name="status",
            new_name="approval_status",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="approved",
        ),
        migrations.AlterField(
            model_name="participant",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="participant",
            name="event_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="zoom_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="registration",
            name="event_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="registration_time",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="registration",
            name="zoom_id",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
