# Generated by Django 4.2.16 on 2024-10-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_joined_time_masterdb_join_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdb',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
